# Site settings
title: Angela Dyrda
description: "iOS Developer"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: "adyrda2"
github_username:  "adyrda2"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed
